### ISSUE TITLE
Clarification re i2c address 0x3b

### ISSUE THREAD

**Issue by DirkUK** [jrmiddle/pisynth#2]
Clarification re 'Note: I have no idea what the "UU" in b30 is about.'.
This means that the address (0x3b in this case) is in use. See http://www.raspberrypi.org/forums/viewtopic.php?f=44&t=81750 for more info on this specific case.

**Comment by jrmiddle** [comment]
Oh thanks! That's really helpful.

**Comment by jrmiddle** [comment]
Updated.
